Root:
    BoxLayout:
        orientation: 'horizontal'
        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: 'Load'
                on_release: root.show_load()
            Button:
                text: 'Chart'
                on_release: root.popup_chart_window()
<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)
<ChartPopup>:

    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"

        Button:
            text: 'Pie'
        Button:
            text: 'Line'
        Button:
            text: 'Scatter'
        Button:
            text: 'Bar'
        